# Generated by Django 5.2 on 2025-05-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=150)),
                ('ni', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('umidade', 'umidade'), ('temperatura', 'temperatura'), ('luminosidade', 'luminosidade'), ('contador', 'contador')], max_length=50)),
                ('mac_address', models.CharField(max_length=20)),
                ('unidade_med', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='app.ambiente')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='app.sensor')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='app.sensor')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='app.sensor')),
            ],
            options={
                'verbose_name_plural': 'Historico',
            },
        ),
    ]
