# Generated by Django 5.2 on 2025-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sensor_timestamp_remove_sensor_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='id_sensor',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
